### ISSUE TITLE
Reliability ?

### ISSUE THREAD

**Issue by MXC48** [sarthakpranesh/PlantRecog#16]
![Screenshot_2022-04-17-13-06-57-090_com.plantrecog.jpg](https://user-images.githubusercontent.com/82712837/163711828-fa6b1efa-926d-4ef2-be3c-64e2c17bb415.jpg)
I think this app lacks a bit of precision 😅
Is this normal? Is there any way to contribute to increase the accuracy?

**Comment by sarthakpranesh** [comment]
Hey @MXC48, model accuracy seems to be fine, the issue here is the request made to Gyan api which scrapes the details of the plant from Google and Wikipedia (refer this section of code https://github.com/sarthakpranesh/PlantRecog/blob/main/services/gyan.ts#L33)

I think we could just make the request using `${name} plant` or something similar to get a better result for this case from Gyan API. It might require some addition changes in Gyan api code too.

If you would like to contribute then try to implement the above suggestion and open a PR if it works, else I'll look into this next weekend for sure.

🚀

**Comment by MXC48** [comment]
> Hey @MXC48, model accuracy seems to be fine, the issue here is the request made to Gyan api which scrapes the details of the plant from Google and Wikipedia (refer this section of code https://github.com/sarthakpranesh/PlantRecog/blob/main/services/gyan.ts#L33)
> 
> I think we could just make the request using `${name} plant` or something similar to get a better result for this case from Gyan API. It might require some addition changes in Gyan api code too.
> 
> If you would like to contribute then try to implement the above suggestion and open a PR if it works, else I'll look into this next weekend for sure.
> 
> 🚀 

I would really like to help you code but unfortunately programming is currently out of my reach...
I can only help you for crash reports or for the translation of the application, sorry.

**Comment by sarthakpranesh** [comment]
@MXC48 check this out - https://github.com/sarthakpranesh/PlantRecog/releases/tag/v1.1.0
Will shortly be on Playstore too

Thank you for opening this issue 😄

**Comment by MXC48** [comment]
I'm testing this update right now and tell you

**Comment by MXC48** [comment]
> @MXC48 check this out - https://github.com/sarthakpranesh/PlantRecog/releases/tag/v1.1.0
> Will shortly be on Playstore too
> 
> Thank you for opening this issue 😄 

![Screenshot_2022-04-18-19-16-29-452_com.plantrecog.jpg](https://user-images.githubusercontent.com/82712837/163846154-394d6af6-6ff2-4125-a54f-20dc03f8ec20.jpg)
It's much better, and I think I understood why he put in "brooms" it's because the plant on the picture is a Cytisus scoparius 😅

**Comment by MXC48** [comment]
Otherwise I take the opportunity to say it here, but I am willing to translate the application in my language, French if possible

**Comment by sarthakpranesh** [comment]
Hey @MXC48, thank you so much for testing and for going out of the way to help me translate the application. Right now I don't have any architecture setup to support translations to different languages but I do know that it is possible with `i18n`. It'll take me some time to implement it in the application once that's done I'll raise an issue for translating the application to different languages and will assign the French translation task to you.

Hope this sounds good 😄

**Comment by MXC48** [comment]
> Hey @MXC48, thank you so much for testing and for going out of the way to help me translate the application. Right now I don't have any architecture setup to support translations to different languages but I do know that it is possible with `i18n`. It'll take me some time to implement it in the application once that's done I'll raise an issue for translating the application to different languages and will assign the French translation task to you.
> 
> Hope this sounds good 😄 

It's perfect👍
