### ISSUE TITLE
Interested in getting this up and running again

### ISSUE THREAD

**Issue by akhil-rasheed** [sarthakpranesh/PlantRecog#25]
Any pointers?

**Comment by sarthakpranesh** [comment]
Hi @akhil-rasheed 
The main problem is hosting the backend. As of now the app requires a backend service which runs the plant detection model. This service used to run on Heroku's free tier, but last year they stopped offering it. I am still looking for a ture alternative to heroku, which needs to be free. I tried using a bunch of other services but they don't have the same offering as Heroku's free tier, and I am not willing to pay as its a hobby project.
Let me know if you have a hosting platform in mind that I can try.

**Comment by akhil-rasheed** [comment]
Hi Pranesh,
I'm not sure what your exact requirements are from the service, but I've had good experiences with both Vercel and Fly on their free tiers. Alternatively, I'd be willing to host temporarily on Google Cloud on my expense, to get the project up and running again. Let me know what you think

**Comment by sarthakpranesh** [comment]
Hi @akhil-rasheed 
Sorry for the super late reply. In the long run I feel running the model locally on device is the way to go, but I am not sure how to achieve that yet (still exploring). I mostly run into issues related with memory on free hosting services, the project requires around 500mb plus (a little over 500mb) which is mostly not available on free triers. I do have a raspberry pi and I was able to host my services their and tunnel them through ngrok. This works for now, services are up and app should be functional. But isn't really a robust solution hence I will be looking into running the model locally. Also looking to implement some new models that improve the accuracy.

**Comment by sarthakpranesh** [comment]
Closing this as project is fully functional again.
